### ISSUE TITLE
Example code available?

### ISSUE THREAD

**Issue by mani76** [ahome-it/ahome-badge#3]
Hello,

Badge is not shown at all. Tried to use following code but the badge is never visible.

Badge b2 = new Badge(memoButton);
b2.setContent(35);
b2.setTheme(BadgeTheme.BLUE);
b2.setPosition(BadgePosition.TOP_RIGHT);
b2.setSize(20);
b2.show();

where memoButton is instance of PushButton and it is shown correctly.

**Comment by eemi2010** [comment]
And what is a PushButton ? Can you please provide a simple entry point that shows the error. Also note that the target element must have the css position relative or absolute. For more informations see the project http://kristerkari.github.io/iOSBadge/ from which ahome-badge is a wrapper

**Comment by mani76** [comment]
Hello,

It is working now, I had to define id for the element.
